sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
before_install: .travis/before_install.sh
after_success: .travis/after_success.sh
script: ./node_modules/.bin/lerna run lint && ./node_modules/.bin/lerna run test
git:
  depth: 1
