sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
script: npm run test:ci

git:
  depth: 1
after_success:
  - ./node_modules/.bin/travis-deploy-once "npm run ci:publish"
