sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
script: npm run test:ci
git:
  depth: 1
before_install:
  - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN -q
  - npm prune
after_success:
  - npm whoami
  - ./node_modules/.bin/travis-deploy-once "npm run ci:publish"
