# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'vs2017-win2016'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g ts-node yarn codecov
      npm install
      npm run ci:setup_env
    displayName: 'Setup environment'
  - script: |
      npm run ci:run_tests
    displayName: 'Run tests'
